# Docker Compose pour VitePress frontend + Webhook Flask

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vitepress_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    command: ["npm", "run", "docs:preview"]
    depends_on:
      - webhook
    networks:
      - commus
    ports:
      - "4173:4173"  # Port par défaut vitepress preview

  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: vitepress_webhook
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - GITHUB_SECRET=${COMMUS_SECRET}
    ports:
      - "9000:9000"
    networks:
      - commus

networks:
  commus:
    driver: bridge
