# Docker Compose pour VitePress frontend + Webhook Flask

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vitepress_frontend
    restart: unless-stopped
    # Plus besoin de volumes car tout est buildé dans l'image
    networks:
      - commus
    ports:
      - "80:80"  # Port standard pour Nginx

  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: vitepress_webhook
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Accès au daemon Docker pour rebuild le frontend
    environment:
      - GITHUB_SECRET=${COMMUS_SECRET}
    ports:
      - "9000:9000"
    networks:
      - commus

networks:
  commus:
    driver: bridge
