services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commus-site
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: bridge
