import {
  pgTable,
  bigserial,
  serial,
  text,
  varchar,
  boolean,
  timestamp,
  integer,
  pgEnum,
  jsonb,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

// ── Enums ──────────────────────────────────────────────

export const sizeCategoryEnum = pgEnum('size_category', [
  'hub_300_plus',
  'very_large_150_plus',
  'large_50_plus',
  'medium_30_plus',
  'medium_under_30',
  'small',
  'unknown',
])

export const communityTypeEnum = pgEnum('community_type', [
  'semi_open_squadron',
  'closed_squadron',
  'open_community',
  'event_only',
  'esport_team',
  'content_creator',
  'mod_development',
  'screenshot_community',
  'atc_community',
  'other',
])

export const recruitmentStatusEnum = pgEnum('recruitment_status', [
  'open',
  'closed',
  'none',
  'unknown',
])

export const eventFrequencyEnum = pgEnum('event_frequency', [
  'very_active',      // + de 3 par semaine
  'very_frequent',    // + d'1 par semaine
  'weekly',           // 1 chaque semaine
  'biweekly',         // 1 toutes les 2 semaines
  'monthly',          // 1 par mois
  'occasional',       // < 1 par mois
  'unknown',
])

export const historicalPeriodEnum = pgEnum('historical_period', [
  'ww2',
  'cold_war_early',
  'cold_war_mid',
  'cold_war_late',
  'gulf_war',
  'early_modern',
  'post_modern',
  'none',
])

export const submissionStatusEnum = pgEnum('submission_status', [
  'pending',
  'approved',
  'rejected',
])

export const memberRoleEnum = pgEnum('member_role', [
  'owner',
  'editor',
])

export const grantedViaEnum = pgEnum('granted_via', [
  'claim_form',   // claim request approved by the admin
  'invite_code',  // invitation link generated by an owner (phase 3)
  'submission',   // submitter of an approved submission
  'admin',        // granted manually from the admin panel
])

export const claimStatusEnum = pgEnum('claim_status', [
  'pending',
  'approved',
  'rejected',
])

export const revisionStatusEnum = pgEnum('revision_status', [
  'pending',
  'approved',
  'rejected',
])

// ── Tables ─────────────────────────────────────────────

export const communities = pgTable('communities', {
  id: serial('id').primaryKey(),
  slug: varchar('slug', { length: 100 }).notNull().unique(),
  name: varchar('name', { length: 255 }).notNull(),
  shortDescription: text('short_description'),
  description: text('description'),
  objectives: text('objectives'),
  logoUrl: text('logo_url'),

  // Enums
  sizeCategory: sizeCategoryEnum('size_category').default('unknown'),
  communityType: communityTypeEnum('community_type').default('other'),
  recruitmentStatus: recruitmentStatusEnum('recruitment_status').default('unknown'),
  eventFrequency: eventFrequencyEnum('event_frequency').default('unknown'),

  // Structured fields
  founder: varchar('founder', { length: 255 }),
  contact: varchar('contact', { length: 255 }),
  entryConditions: text('entry_conditions'),
  sizeText: varchar('size_text', { length: 255 }),

  // Links
  discordUrl: text('discord_url'),
  websiteUrl: text('website_url'),
  youtubeUrl: text('youtube_url'),
  instagramUrl: text('instagram_url'),
  facebookUrl: text('facebook_url'),
  twitchUrl: text('twitch_url'),
  twitterUrl: text('twitter_url'),
  otherLinks: jsonb('other_links').$type<{ label: string; url: string }[]>(),

  // Meta
  featured: boolean('featured').default(false),
  published: boolean('published').default(true),
  isCommunityPillar: boolean('is_community_pillar').default(false),
  votes: integer('votes').default(0),
  foundedDate: varchar('founded_date', { length: 50 }),

  // Managed by the community itself (phase 3). Accent is validated against a
  // closed palette server-side so the directory stays visually coherent.
  accentColor: varchar('accent_color', { length: 20 }),
  bannerUrl: text('banner_url'),

  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const modules = pgTable('modules', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 100 }).notNull().unique(),
  category: varchar('category', { length: 50 }), // 'western_fixed', 'eastern_fixed', 'helicopter', 'ww2', 'other'
  iconUrl: text('icon_url'),
})

export const experiences = pgTable('experiences', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull().unique(),
  slug: varchar('slug', { length: 100 }).notNull().unique(),
  icon: varchar('icon', { length: 50 }),
  category: varchar('category', { length: 50 }), // 'mission_role', 'gameplay', 'skill_level', 'infrastructure'
})

export const communityModules = pgTable('community_modules', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  moduleId: integer('module_id').notNull().references(() => modules.id, { onDelete: 'cascade' }),
})

export const communitySoughtModules = pgTable('community_sought_modules', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  moduleId: integer('module_id').notNull().references(() => modules.id, { onDelete: 'cascade' }),
})

export const communityExperiences = pgTable('community_experiences', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  experienceId: integer('experience_id').notNull().references(() => experiences.id, { onDelete: 'cascade' }),
})

export const communityHistoricalPeriods = pgTable('community_historical_periods', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  period: historicalPeriodEnum('period').notNull(),
})

export const communityImages = pgTable('community_images', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  url: text('url').notNull(),
  alt: varchar('alt', { length: 255 }),
  sortOrder: integer('sort_order').default(0),
})

export const communityVotes = pgTable('community_votes', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  sessionId: varchar('session_id', { length: 64 }).notNull(),
  ipHash: varchar('ip_hash', { length: 64 }).notNull(),
  fingerprintHash: varchar('fingerprint_hash', { length: 64 }).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, table => ({
  uniqueSessionVote: uniqueIndex('idx_community_votes_session_unique').on(table.communityId, table.sessionId),
  communityLookup: index('idx_community_votes_community').on(table.communityId),
  ipCreatedLookup: index('idx_community_votes_ip_created').on(table.ipHash, table.createdAt),
  fingerprintCreatedLookup: index('idx_community_votes_fingerprint_created').on(table.fingerprintHash, table.createdAt),
}))

export const submissions = pgTable('submissions', {
  id: serial('id').primaryKey(),
  communityName: varchar('community_name', { length: 255 }).notNull(),
  contactName: varchar('contact_name', { length: 255 }).notNull(),

  // Core info
  shortDescription: text('short_description'),
  description: text('description'),
  objectives: text('objectives'),
  logoUrl: text('logo_url'),

  // Enums (stored as text to avoid enum constraint issues - validated in code)
  communityType: text('submission_community_type'),
  sizeCategory: text('submission_size_category'),
  recruitmentStatus: text('submission_recruitment_status'),
  eventFrequency: text('submission_event_frequency'),

  // Structured fields
  founder: varchar('founder', { length: 255 }),
  entryConditions: text('entry_conditions'),
  sizeText: varchar('size_text', { length: 255 }),

  // Links
  discordUrl: text('discord_url'),
  websiteUrl: text('website_url'),
  youtubeUrl: text('youtube_url'),
  instagramUrl: text('instagram_url'),
  facebookUrl: text('facebook_url'),
  twitchUrl: text('twitch_url'),
  twitterUrl: text('twitter_url'),
  otherLinks: jsonb('submission_other_links').$type<{ label: string; url: string }[]>(),

  // Modules & experiences (stored as JSON arrays of names)
  moduleNames: jsonb('submission_module_names').$type<string[]>(),
  soughtModuleNames: jsonb('submission_sought_module_names').$type<string[]>(),
  experienceNames: jsonb('submission_experience_names').$type<string[]>(),
  historicalPeriods: jsonb('submission_historical_periods').$type<string[]>(),

  // Images (stored as JSON)
  images: jsonb('submission_images').$type<{ url: string; alt: string | null }[]>(),

  // Admin workflow
  status: submissionStatusEnum('status').default('pending'),
  adminNotes: text('admin_notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),

  // Set when the submitter was signed in — they become owner on approval.
  submittedByUserId: integer('submitted_by_user_id').references(() => users.id, { onDelete: 'set null' }),
})

// ── Accounts & community management ────────────────────

/** Discord-backed identity. No password, no secret is ever stored here. */
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  discordId: varchar('discord_id', { length: 32 }).notNull().unique(),
  discordUsername: varchar('discord_username', { length: 100 }).notNull(),
  discordAvatarUrl: text('discord_avatar_url'),
  isBlocked: boolean('is_blocked').notNull().default(false),
  lastLoginAt: timestamp('last_login_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

/** Binds a user to a community they are allowed to manage. */
export const communityMembers = pgTable('community_members', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  role: memberRoleEnum('role').notNull().default('editor'),
  grantedVia: grantedViaEnum('granted_via').notNull(),
  invitedByUserId: integer('invited_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, table => ({
  uniqueMembership: uniqueIndex('idx_community_members_unique').on(table.communityId, table.userId),
  byUser: index('idx_community_members_user').on(table.userId),
}))

/** "I manage this community" requests, reviewed by the admin. */
export const claimRequests = pgTable('claim_requests', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  message: text('message'),
  status: claimStatusEnum('status').notNull().default('pending'),
  adminNote: text('admin_note'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  resolvedAt: timestamp('resolved_at'),
}, table => ({
  uniqueRequest: uniqueIndex('idx_claim_requests_unique').on(table.communityId, table.userId),
  byStatus: index('idx_claim_requests_status').on(table.status),
}))

/** Extra titled sections a community adds to its own page (max 4, enforced in code). */
export const communitySections = pgTable('community_sections', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  title: varchar('title', { length: 80 }).notNull(),
  body: text('body').notNull(), // markdown, sanitized at render time
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, table => ({
  byCommunity: index('idx_community_sections_community').on(table.communityId, table.sortOrder),
}))

/**
 * Single-use invitation links generated by an owner to add a co-editor.
 * The clear code is shown once; only its hash is stored.
 */
export const inviteCodes = pgTable('invite_codes', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  codeHash: varchar('code_hash', { length: 64 }).notNull().unique(),
  grantsRole: memberRoleEnum('grants_role').notNull().default('editor'),
  createdByUserId: integer('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  expiresAt: timestamp('expires_at').notNull(),
  usedByUserId: integer('used_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  usedAt: timestamp('used_at'),
  revokedAt: timestamp('revoked_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, table => ({
  byCommunity: index('idx_invite_codes_community').on(table.communityId),
}))

/**
 * Pending changes to sensitive fields (name, links, images), held for admin
 * review. At most one pending row per community: a later save merges into it.
 */
export const communityRevisions = pgTable('community_revisions', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  userId: integer('user_id').references(() => users.id, { onDelete: 'set null' }),
  fieldsPatch: jsonb('fields_patch').$type<Record<string, unknown>>().notNull(),
  status: revisionStatusEnum('status').notNull().default('pending'),
  adminNote: text('admin_note'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  reviewedAt: timestamp('reviewed_at'),
}, table => ({
  byStatus: index('idx_community_revisions_status').on(table.status),
  byCommunity: index('idx_community_revisions_community').on(table.communityId),
}))

/**
 * Per-community traffic, aggregated by day and type.
 *
 * Counters only — no per-visitor row, no identifier of any kind — so this adds
 * nothing to the site's privacy footprint while still telling a manager whether
 * their page is working.
 */
export const communityEvents = pgTable('community_events', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  type: varchar('type', { length: 30 }).notNull(), // 'view' | 'click_discord' | 'click_<network>'
  day: varchar('day', { length: 10 }).notNull(),   // YYYY-MM-DD, Paris time
  count: integer('count').notNull().default(0),
}, table => ({
  uniqueEvent: uniqueIndex('idx_community_events_unique').on(table.communityId, table.type, table.day),
  byCommunity: index('idx_community_events_community').on(table.communityId, table.day),
}))

/** Full copy of a community taken before each edit, so any save can be undone. */
export const communitySnapshots = pgTable('community_snapshots', {
  id: serial('id').primaryKey(),
  communityId: integer('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
  userId: integer('user_id').references(() => users.id, { onDelete: 'set null' }),
  data: jsonb('data').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, table => ({
  byCommunity: index('idx_community_snapshots_community').on(table.communityId, table.createdAt),
}))

// ── Relations ──────────────────────────────────────────

export const communitiesRelations = relations(communities, ({ many }) => ({
  modules: many(communityModules),
  soughtModules: many(communitySoughtModules),
  experiences: many(communityExperiences),
  historicalPeriods: many(communityHistoricalPeriods),
  images: many(communityImages),
  votesLedger: many(communityVotes),
  members: many(communityMembers),
  claimRequests: many(claimRequests),
  snapshots: many(communitySnapshots),
  revisions: many(communityRevisions),
  sections: many(communitySections),
}))

export const communitySectionsRelations = relations(communitySections, ({ one }) => ({
  community: one(communities, { fields: [communitySections.communityId], references: [communities.id] }),
}))

export const inviteCodesRelations = relations(inviteCodes, ({ one }) => ({
  community: one(communities, { fields: [inviteCodes.communityId], references: [communities.id] }),
}))

export const communityRevisionsRelations = relations(communityRevisions, ({ one }) => ({
  community: one(communities, { fields: [communityRevisions.communityId], references: [communities.id] }),
  user: one(users, { fields: [communityRevisions.userId], references: [users.id] }),
}))

export const usersRelations = relations(users, ({ many }) => ({
  memberships: many(communityMembers),
  claimRequests: many(claimRequests),
}))

export const communityMembersRelations = relations(communityMembers, ({ one }) => ({
  community: one(communities, { fields: [communityMembers.communityId], references: [communities.id] }),
  user: one(users, { fields: [communityMembers.userId], references: [users.id] }),
}))

export const claimRequestsRelations = relations(claimRequests, ({ one }) => ({
  community: one(communities, { fields: [claimRequests.communityId], references: [communities.id] }),
  user: one(users, { fields: [claimRequests.userId], references: [users.id] }),
}))

export const communitySnapshotsRelations = relations(communitySnapshots, ({ one }) => ({
  community: one(communities, { fields: [communitySnapshots.communityId], references: [communities.id] }),
  user: one(users, { fields: [communitySnapshots.userId], references: [users.id] }),
}))

export const communityModulesRelations = relations(communityModules, ({ one }) => ({
  community: one(communities, { fields: [communityModules.communityId], references: [communities.id] }),
  module: one(modules, { fields: [communityModules.moduleId], references: [modules.id] }),
}))

export const communitySoughtModulesRelations = relations(communitySoughtModules, ({ one }) => ({
  community: one(communities, { fields: [communitySoughtModules.communityId], references: [communities.id] }),
  module: one(modules, { fields: [communitySoughtModules.moduleId], references: [modules.id] }),
}))

export const communityExperiencesRelations = relations(communityExperiences, ({ one }) => ({
  community: one(communities, { fields: [communityExperiences.communityId], references: [communities.id] }),
  experience: one(experiences, { fields: [communityExperiences.experienceId], references: [experiences.id] }),
}))

export const communityHistoricalPeriodsRelations = relations(communityHistoricalPeriods, ({ one }) => ({
  community: one(communities, { fields: [communityHistoricalPeriods.communityId], references: [communities.id] }),
}))

export const communityImagesRelations = relations(communityImages, ({ one }) => ({
  community: one(communities, { fields: [communityImages.communityId], references: [communities.id] }),
}))

export const communityVotesRelations = relations(communityVotes, ({ one }) => ({
  community: one(communities, { fields: [communityVotes.communityId], references: [communities.id] }),
}))

export const modulesRelations = relations(modules, ({ many }) => ({
  communities: many(communityModules),
  soughtBy: many(communitySoughtModules),
}))

export const experiencesRelations = relations(experiences, ({ many }) => ({
  communities: many(communityExperiences),
}))

// ── Streamers ──────────────────────────────────────────

export const streamers = pgTable('streamers', {
  id: serial('id').primaryKey(),
  twitchId: text('twitch_id').notNull().unique(),
  twitchLogin: varchar('twitch_login', { length: 100 }).notNull().unique(),
  displayName: varchar('display_name', { length: 255 }).notNull(),
  description: text('description'),
  profileImageUrl: text('profile_image_url'),
  // Live on Twitch, whatever the game. Since we poll our streamers by user id
  // (to separate DCS time from total airtime), this alone no longer means
  // "live on DCS" — pair it with currentGameId for that.
  isLive: boolean('is_live').default(false),
  currentGameId: varchar('current_game_id', { length: 32 }),
  lastStreamTitle: text('last_stream_title'),
  lastStreamStartedAt: timestamp('last_stream_started_at'),
  currentViewers: integer('current_viewers').default(0),
  communityId: integer('community_id').references(() => communities.id, { onDelete: 'set null' }),
  isActive: boolean('is_active').default(true),

  // Channel-level language, more stable than the per-stream one: many French
  // streamers never tag the stream itself as fr.
  broadcasterLanguage: varchar('broadcaster_language', { length: 10 }),
  // 'partner' | 'affiliate' | '' — a free proxy for channel size.
  broadcasterType: varchar('broadcaster_type', { length: 20 }),
  // Result of the FR classifier; overridable by an admin (see frenchOverride).
  isFrench: boolean('is_french').default(true),
  // When set, wins over the classifier — lets an admin fix a wrong guess.
  frenchOverride: boolean('french_override'),
  followers: integer('followers'),

  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

/**
 * One observation of a live stream, taken every poll.
 *
 * Twitch archives nothing: viewer counts, titles and session boundaries exist
 * only while the stream is live. Everything downstream (sessions, daily stats,
 * curves) is derived from this table, so a gap here is a permanent hole.
 */
export const streamerSamples = pgTable('streamer_samples', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  streamerId: integer('streamer_id').notNull().references(() => streamers.id, { onDelete: 'cascade' }),
  // Twitch's own stream id — groups samples into a session with no guesswork.
  streamId: varchar('stream_id', { length: 32 }).notNull(),
  observedAt: timestamp('observed_at').defaultNow().notNull(),
  viewerCount: integer('viewer_count').notNull().default(0),
  gameId: varchar('game_id', { length: 32 }),
  title: text('title'),
}, table => ({
  uniqueObservation: uniqueIndex('idx_streamer_samples_unique').on(table.streamerId, table.streamId, table.observedAt),
  byStreamer: index('idx_streamer_samples_streamer').on(table.streamerId, table.observedAt),
  byStream: index('idx_streamer_samples_stream').on(table.streamId),
}))

/**
 * A stream session, maintained incrementally as samples arrive.
 *
 * `startedAt` comes straight from Twitch and is exact; `lastSeenAt` is the last
 * poll that still saw the stream, so the end is precise to one poll interval.
 * Sums are kept alongside counts so averages never need a scan of the samples.
 */
export const streamerSessions = pgTable('streamer_sessions', {
  id: serial('id').primaryKey(),
  streamerId: integer('streamer_id').notNull().references(() => streamers.id, { onDelete: 'cascade' }),
  streamId: varchar('stream_id', { length: 32 }).notNull().unique(),
  startedAt: timestamp('started_at').notNull(),
  lastSeenAt: timestamp('last_seen_at').notNull(),
  isLive: boolean('is_live').notNull().default(true),
  sampleCount: integer('sample_count').notNull().default(0),
  dcsSampleCount: integer('dcs_sample_count').notNull().default(0),
  viewerSum: integer('viewer_sum').notNull().default(0),
  peakViewers: integer('peak_viewers').notNull().default(0),
  titles: jsonb('titles').$type<string[]>(),
  vodUrl: text('vod_url'),
  vodDuration: varchar('vod_duration', { length: 16 }),
  vodViewCount: integer('vod_view_count'),
}, table => ({
  byStreamer: index('idx_streamer_sessions_streamer').on(table.streamerId, table.startedAt),
  byLive: index('idx_streamer_sessions_live').on(table.isLive),
}))

/** Daily rollup, kept forever — raw samples are purged after 90 days. */
export const streamerDailyStats = pgTable('streamer_daily_stats', {
  streamerId: integer('streamer_id').notNull().references(() => streamers.id, { onDelete: 'cascade' }),
  day: varchar('day', { length: 10 }).notNull(), // YYYY-MM-DD, Paris time
  dcsMinutes: integer('dcs_minutes').notNull().default(0),
  totalMinutes: integer('total_minutes').notNull().default(0),
  sessions: integer('sessions').notNull().default(0),
  peakViewers: integer('peak_viewers').notNull().default(0),
  avgViewers: integer('avg_viewers').notNull().default(0),
}, table => ({
  pk: uniqueIndex('idx_streamer_daily_stats_pk').on(table.streamerId, table.day),
  byDay: index('idx_streamer_daily_stats_day').on(table.day),
}))

/**
 * Follower count over time.
 *
 * Deliberately its own table: reading the total with an app token is an
 * undocumented behaviour that Twitch could remove at any time, and nothing else
 * must break when it does.
 */
export const streamerFollowerHistory = pgTable('streamer_follower_history', {
  streamerId: integer('streamer_id').notNull().references(() => streamers.id, { onDelete: 'cascade' }),
  day: varchar('day', { length: 10 }).notNull(),
  followers: integer('followers').notNull(),
}, table => ({
  pk: uniqueIndex('idx_streamer_follower_history_pk').on(table.streamerId, table.day),
}))

export const streamerDcsDays = pgTable('streamer_dcs_days', {
  id: serial('id').primaryKey(),
  streamerId: integer('streamer_id').notNull().references(() => streamers.id, { onDelete: 'cascade' }),
  date: varchar('date', { length: 10 }).notNull(), // YYYY-MM-DD in Paris tz
  createdAt: timestamp('created_at').defaultNow(),
})

// ── Streamer Relations ─────────────────────────────────

export const streamersRelations = relations(streamers, ({ one, many }) => ({
  community: one(communities, { fields: [streamers.communityId], references: [communities.id] }),
  dcsDays: many(streamerDcsDays),
  samples: many(streamerSamples),
  sessions: many(streamerSessions),
  dailyStats: many(streamerDailyStats),
  followerHistory: many(streamerFollowerHistory),
}))

export const streamerSamplesRelations = relations(streamerSamples, ({ one }) => ({
  streamer: one(streamers, { fields: [streamerSamples.streamerId], references: [streamers.id] }),
}))

export const streamerSessionsRelations = relations(streamerSessions, ({ one }) => ({
  streamer: one(streamers, { fields: [streamerSessions.streamerId], references: [streamers.id] }),
}))

export const streamerDailyStatsRelations = relations(streamerDailyStats, ({ one }) => ({
  streamer: one(streamers, { fields: [streamerDailyStats.streamerId], references: [streamers.id] }),
}))

export const streamerDcsDaysRelations = relations(streamerDcsDays, ({ one }) => ({
  streamer: one(streamers, { fields: [streamerDcsDays.streamerId], references: [streamers.id] }),
}))
