name: Deploy to production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permet le déclenchement manuel depuis l'interface GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH keys and known hosts
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H kerboul.me >> ~/.ssh/known_hosts
      
      - name: Deploy to Production
        run: |
          echo "Exécution du script de déploiement via SSH..."
          ssh -o StrictHostKeyChecking=accept-new root@kerboul.me "ssh docker-light 'cd ~/commus_dcs && bash deploy.sh'"
          
          echo "Déploiement terminé avec succès!"
