name: Trigger SSH Script

on:
  push:
    branches:
      - main

jobs:
  run-ssh-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Check npm version
        run: npm --version

      - name: Install dependencies
        run: npm install

      - name: Install Vitepress
        run: npm add -D vitepress

      - name: Build Website
        run: npm run docs:build

      - name: Nettoyage Fichiers Temporaires
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Running SSH script..."
            ls -l
  
      - name: Copy dist folder using scp
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r ./docs/.vitepress/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/kerboul/serveur_web/commus_temp/
          rm -f ~/.ssh/id_rsa
  
      - name: Execute SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Running SSH script..."
            echo "BIDULE"
