name: Trigger SSH Script

on:
  push:
    branches:
      - main

jobs:
  run-ssh-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Check npm version
        run: npm --version

      - name: Install dependencies
        run: npm install

      - name: Install Vitepress
        run: npm add -D vitepress

      - name: Build Website
        run: npm run docs:build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vitepress-dist
          path: ./docs/.vitepress/dist