name: Déploiement du site

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Install dependencies
        run: npm install

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Lint Markdown
        run: npm run lint:md

  site-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Check npm version
        run: npm --version

      - name: Install dependencies
        run: npm install

      - name: Install Vitepress
        run: npm add -D vitepress

      - name: Build Website
        run: npm run docs:build

      - name: Préparation du déplacement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Running SSH script..."
            cd /home/kerboul/temp_github
            mkdir site_commus
  
      - name: Déplacement du site construit via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r -v ./docs/.vitepress/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/kerboul/temp_github/site_commus
          rm -f ~/.ssh/id_rsa
  
      - name: Application des changements et update du site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/kerboul/temp_github/site_commus
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" . kerboul@mikoshi:/home/kerboul/serveur_web/commus_dcs_wip/
            ssh kerboul@mikoshi "rm -rf /home/kerboul/serveur_web/commus_dcs/* && mv /home/kerboul/serveur_web/commus_dcs_wip/* /home/kerboul/serveur_web/commus_dcs/"
            cd /home/kerboul/temp_github
            rm -rf site_commus
